usage: prepare_3dpredictor.py [-h] --dataset DATASET -c CELL -od OUTDIR
                              [--bin-size BIN_SIZE]
                              [--gimme_config GIMME_CONFIG]
                              [--np_config NP_CONFIG] [-t NTHREADS]
prepare_3dpredictor.py: error: the following arguments are required: --dataset

# PROG: 'prepare_3dpredictor.py' started at Mon Aug  9 22:27:47 2021
## PWD: /home/chenken/Documents/DeepEPI/related/3DPredictor
## CMD: ./prepare_3dpredictor.py ../../data/BENGI/GM12878.HiC-Benchmark.v3.tsv -c GM12878 -od ./tmp_CTCF
## ARG: Namespace(bin_size=5000, cell='GM12878', dataset='../../data/BENGI/GM12878.HiC-Benchmark.v3.tsv', gimme_config='/data2/users/chenken/Documents/EPIGL/data/gimme/gimme_new.json', np_config='/data2/users/chenken/Documents/EPIGL/data/bed_config/epigenetic.json', nthreads=16, outdir='./tmp_CTCF')
Processing ../../data/BENGI/GM12878.HiC-Benchmark.v3.tsv ... Mon Aug  9 22:27:47 2021
Traceback (most recent call last):
  File "./prepare_3dpredictor.py", line 270, in <module>
    parse_gimme_peaks(args.cell, args.dataset, outdir, args.gimme_config)
  File "./prepare_3dpredictor.py", line 148, in parse_gimme_peaks
    config = json.load(open(oriented_gimme_config))
FileNotFoundError: [Errno 2] No such file or directory: '/data2/users/chenken/Documents/EPIGL/data/gimme/gimme_new.json'

# PROG: 'prepare_3dpredictor.py' started at Mon Aug  9 22:27:55 2021
## PWD: /home/chenken/Documents/DeepEPI/related/3DPredictor
## CMD: ./prepare_3dpredictor.py ../../data/BENGI/GM12878.HiC-Benchmark.v3.tsv -c GM12878 -od ./tmp_CTCF
## ARG: Namespace(bin_size=5000, cell='GM12878', dataset='../../data/BENGI/GM12878.HiC-Benchmark.v3.tsv', gimme_config='/data2/users/chenken/Documents/EPIGL/data/gimme/gimme_new.json', np_config='/data2/users/chenken/Documents/EPIGL/data/bed_config/epigenetic.json', nthreads=16, outdir='./tmp_CTCF')
Processing ../../data/BENGI/GM12878.HiC-Benchmark.v3.tsv ... Mon Aug  9 22:27:55 2021
Traceback (most recent call last):
  File "./prepare_3dpredictor.py", line 270, in <module>
    parse_gimme_peaks(args.cell, args.dataset, outdir, args.gimme_config)
  File "./prepare_3dpredictor.py", line 148, in parse_gimme_peaks
    config = json.load(open(oriented_gimme_config))
FileNotFoundError: [Errno 2] No such file or directory: '/data2/users/chenken/Documents/EPIGL/data/gimme/gimme_new.json'

# PROG: 'prepare_3dpredictor.py' started at Mon Aug  9 22:28:42 2021
## PWD: /home/chenken/Documents/DeepEPI/related/3DPredictor
## CMD: ./prepare_3dpredictor.py ../../data/BENGI/GM12878.HiC-Benchmark.v3.tsv -c GM12878 -od ./tmp_CTCF
## ARG: Namespace(bin_size=5000, cell='GM12878', dataset='../../data/BENGI/GM12878.HiC-Benchmark.v3.tsv', gimme_config='/home/chenken/Documents/DeepEPI/data/genomic_features/gimme/gimme_new.json', nthreads=16, outdir='./tmp_CTCF')
Processing ../../data/BENGI/GM12878.HiC-Benchmark.v3.tsv ... Mon Aug  9 22:28:42 2021
./prepare_3dpredictor.py:150: UserWarning: Only use CTCF
  warn("Only use CTCF") # %XXX
mkdir: cannot create directory ‘./features_3D’: File exists
mkdir: cannot create directory ‘./features_3D’: File exists
